POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "url": "https://overreacted.io/things-i-don't-know-as-of-2018/", 
    "title": "Things I Don't Know as of 2018",
    "author": "Dan Abramov",
    "userId": "5e4b375f337b4c3dfbd67cac",
    "likes": 0
}