POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1ZTRiMzc1ZjMzN2I0YzNkZmJkNjdjYWMiLCJpYXQiOjE1ODIwMzc4NTd9.g0XR7G9AV0vrTGKSNREPoO9fku4t6C7gPoF-plvNqs0

{
    "url": "https://overreacted.io/things-i-don't-know-as-of-2018/", 
    "title": "Things I Don't Know as of 2018",
    "author": "Dan Abramovich",
    "userId": "5e4b375f337b4c3dfbd67cac",
    "likes": 0
}